### ISSUE TITLE
pluginLibrary tiddler contains transclusions

### ISSUE THREAD

**Issue by pmario** [flibbles/tw5-relink#27]
Hi 
Your plugin library tiddler: https://github.com/flibbles/tw5-relink/blob/master/plugins/relink/tiddlers/pluginLibrary.tid contains transclusions like this: {{$:/plugins/flibbles/relink/language/PluginLibrary/Hint}}

I would like to ship the config-tiddler with some of my editions. When I build the edition I want to dynamically load that tiddler, which should contain the link to the "latest" version. 

The transclusions make it hard, because I would need to include several tiddlers, which I don't want. ...

**Comment by flibbles** [comment]
Is this [updated pluginTiddler](https://github.com/flibbles/tw5-relink/blob/master/plugins/relink/tiddlers/pluginLibrary.tid) work?

**Comment by pmario** [comment]
I'll test and close the issue if yes ;)

**Comment by flibbles** [comment]
Do you need this change to be pushed to the very plugin the pluginlibrary tiddler is pointing to? If so, I can release a new Relink version for this.

**Comment by pmario** [comment]
I think, if you provide an independent tiddler, that you keep up-to-date, you don't need to change the tiddler in your library.

**Comment by pmario** [comment]
So you can keep the language specific one. ... If that's possible??? .. May be we will create 2 tabs in the library dialogue that way. ... Do you know, what I mean?

**Comment by flibbles** [comment]
Honestly, I don't mind having the strings hardcoded like that. Tiddlywiki doesn't actually have a mechanism for localizing plugins. I just did so that one day in the future it wouldn't be a buttload of work to convert it if necessary.

My only concern is making a new release that doesn't add any new features. So if having the plugintiddler in github is sufficient, I'd probably leave it at that until I have something more substantial to release.

**Comment by pmario** [comment]
I'm OK with the version at github. I can load it from there. No plugin version needed. So closing the issue.

**Comment by pmario** [comment]
Thx for the fast reply!

**Comment by flibbles** [comment]
No worries! I've been meaning to make this change for a while anyway.
