### ISSUE TITLE
add a backlinks section on the official docs

### ISSUE THREAD

**Issue by IE404** [flibbles/tw5-relink#38]
hi and thanks for your great work on this plugin. i have a little request.

i read here ( https://groups.google.com/g/tiddlywiki/c/C_svkYnZubA ) that i can use your plugin to create a backlink section into all my tiddlers. so i added this into the view template ov my tiddlers 

{{||$:/plugins/flibbles/relink/ui/TiddlerInfo/References}}

i have tiddlers with a custom field named "description" which contains text like "i want to link to [[Record]] but this dienst show up"

On the tiddler Record i can see every Link to this tiddler, except links from tiddlers where the wikilink is in the description.

is this out of scope of your plugin or am i missing something?

i also added unter config -> Operators "field:description" as wikitext but it doenst work.

could you eloberate a bit more in the doc, how one can display the backlinks?

**Comment by flibbles** [comment]
You need to use the "Fields" tab instead of the "Operators" tab. Add an entry called "description", and set the dropdown to wikitext.

I understand why you put it in "operators" as "field:description". The "field:title" entry is there, but that concerns the filter operator `[field:title[]]`.

The documentation can probably be clarified a bit, so I'll leave this issue open until I put out the next release.

**Comment by IE404** [comment]
thank you for clarifying that. now it works for my usecase

**Comment by flibbles** [comment]
Documentation clarified
