### ISSUE TITLE
[IDEA] Configuration Setting to Determine if modified Field is Updated

### ISSUE THREAD

**Issue by yaisog** [flibbles/tw5-relink#39]
Just as the title says, I propose to add an option not to update the `modified` field when relinking. Since relinking is not an edit that I consciously apply to a tiddler, it messes up my sorting by last edited date.
Other than that, awesome plugin!
Have a great day
Yaisog

**Comment by flibbles** [comment]
Might be nice. I haven't been involved with Relink in a while, or even TiddlyWiki really. There probably will be a new version eventually, and perhaps I'll put in this feature, though it's actually more of a core issue than a relink issue. core does some relinking too without TW5-Relink, and it always touches the modified field. It's not possible to stop it without changing the javascript because nobody thought to pass the options argument through.

In the meantime, you can disable it for your build by editing the shadow tiddler `$:/plugins/flibbles/relink/js/bulkops.js` and changing one line in the file from being this:

```javascript
            var newTiddler = new $tw.Tiddler(tiddler,changes,this.getModificationFields())
```
to this:
```javascript
            var newTiddler = new $tw.Tiddler(tiddler,changes)
```

That'll do it, though I haven't tested it. I'll leave this issue open in the meantime.

**Comment by yaisog** [comment]
Thanks, I'll try that.
Hope to see you back soon in the TW community!
Have a nice day
Yaisog
