### ISSUE TITLE
Can relink references be expanded to give more context by providing word highlighting of the linked words

### ISSUE THREAD

**Issue by arunnbabu81** [flibbles/tw5-relink#41]
This is a example of word highlighting of references in an app called remnote.

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/67494083/177209981-50e3172e-680e-4a6d-9903-d98f6bd3a8ed.png">

In TW, if I am using the relink reference tab, this look like this.

<img width="578" alt="image" src="https://user-images.githubusercontent.com/67494083/177210030-4d192c1d-e9b9-4c79-bcfe-c44588823386.png">

I know that there is backlinks option in stroll edition of TW with word highlighting - but its based on the context plug in.

Can a similar word highlighting be added to relink references.

This is not an issue, but just an idea or suggestion.

**Comment by flibbles** [comment]
I expect I'll mark this as out of scope. If those `[[Peter Kranz]]` were color coded, which I think means they'd be light blue like other links, people would expect they could click them. And logically they'd only go to the very tiddler the user is already viewing.

Also, the blurbs supplied by the References tab are representations of the underlying text rather than what is rendered. (For instance `{{!!field}}` instead of showing the value of the field being transcluded.) For that reason, I think the color coding would only be applicable to prettyLinks. I can't think of any others off hand which would have an intuitive coloring.
