### ISSUE TITLE
[Bug] `$:/tags/Global` for macro and procedure definitions not recognized by Relink

### ISSUE THREAD

**Issue by mateuszwilczek** [flibbles/tw5-relink#48]
**Steps to reproduce:**

1. Define a macro that takes a tiddler title as a parameter.
2. Tag the definition tiddler with `$:/tags/Macro`.
3. Define the macro and parameter in Relink config, indicating that the parameter is a title.
4. Call the macro in tiddler A, use tiddler B as parameter.
5. Relink recognizes the reference from A to B (e.g. A is shown in B's Relink References info tab), as expected.
6. Change the `$:/tags/Macro` tag on macro definition to `$:/tags/Global`.

**Expected behavior:**
Macro works the same and Relink recognizes it the same (e.g. A is shown in B's Relink References info tab).

**Actual behavior:**
Macro works the same, but Relink no longer recognizes it (e.g. A is not shown in B's Relink References info tab).

The situation is identical for a procedure instead of macro.
I have only tested it with a parameter that is a _title_, I have not tested it with other types of parameters (_filter, list, refererence, wikitext_) yet.

As far as I have tested, user defined functions/operators seem to be recognized by Relink correctly, regardless if tagged with `$:/tags/Macro` or `$:/tags/Global`.

Tested on an empty TW v5.3.1 with Relink v2.3.5 and no other plugins.

**Comment by flibbles** [comment]
`$:/tags/Global` must be something new. I've never heard of it before. (So yeah, it wouldn't be implemented.) Does it work the same way `$:/tags/Macro` works? Or is it something different?

**Comment by mateuszwilczek** [comment]
It was introduced in v5.3.0 along with procedures and functions, as a more properly named tag for all global definitions (macros, procedures, functions).
It's supposed to work identically to `$:/tags/Macro`, see [documentation](https://tiddlywiki.com/#SystemTag%3A%20%24%3A%2Ftags%2FMacro:%5B%5BSystemTag%3A%20%24%3A%2Ftags%2FMacro%5D%5D%20%5B%5BSystemTag%3A%20%24%3A%2Ftags%2FGlobal%5D%5D).

**Comment by flibbles** [comment]
All right. It'll take me a few days to find the time, but I'll implement `$:/tags/Global`, and procedures too.

Maybe not functions yet. Not unless you are using them.

(I'll be honest with you. A lot of the new features in v5.3.0 baffle me. I can hardly make sense of some of them, much less think of use cases for them, so I've been putting off implementing those features until someone actually submits a bug for them. Because I secretly suspected that no one is actually using those features.)

**Comment by mateuszwilczek** [comment]
> All right. It'll take me a few days to find the time, but I'll implement `$:/tags/Global`, and procedures too.

Thanks! This isn't critical, as one can use the `$:/tags/Macro`, as I do right now, and everything works alright. There is really no benefit of `$:/tags/Global` over `$:/tags/Macro` other than it being clearer what it does.

Also the issue is only when calling macro with unnamed parameters like `<<my-macro B>>`, because then I assume Relink has to find the macro definition to know the order of unnamed parameters (and it can't find it now unless tagged with `$:/tags/Macro`).
Everything works regardless of the tag if macro is called with named parameters like `<<my-macro param:"B">>`.

> Maybe not functions yet. Not unless you are using them.

It might be that there's no need to do anything. If I guess correctly, Relink needs the macro/procedure definition only to know the order of unnamed parameters. This is not an issue for functions/operators. I haven't encountered any problem with them so far.

> (I'll be honest with you. A lot of the new features in v5.3.0 baffle me. I can hardly make sense of some of them, much less think of use cases for them, so I've been putting off implementing those features until someone actually submits a bug for them. Because I secretly suspected that no one is actually using those features.)

I find some of them very helpful. But I understand it must be difficult to keep a plugin like Relink up to date with all of them. All the more reason to thank you for your support!

**Comment by flibbles** [comment]
This should work now.

I also went ahead and implemented `\function`, `\procedure`, and `\widget`, but that's it. I'm still not clambering to create full v5.3.x support, because I disagree with the idea that these features are useful.

They are not. They are three new pragmas subtly different from the existing pragma that mostly serve to confuse newcomers. I really feel that TiddlyWiki development needs to stop bloating itself with more and more specific features and start improving its support for plugins. `\function`, `\procedure`, and `\widget` could have been great features added as a plugin. (Especially given how not a single one of them is used by the core.)
