### ISSUE TITLE
tag to tiddler - cannot change name

### ISSUE THREAD

**Issue by hchaase** [flibbles/tw5-relink#5]
Hope it makes sense. Its a bit hard to explain

1. I make a new tiddler with a new tag (action)
2. I make the tag (action) a tiddler with a toc in the text field
3. I rename the new tag-tiddler (action) to Husk:action
4A. I get an error, 
4B. a tiddler with the new name Husk:action is created 
4C. the tag in the new tiddler from step 1 is NOT changed
4D. I cannot save the new tiddler and get a warning that a tiddler with the new mane already exist (see 4B)

I had to delete the original tag-tiddler (action), use the new created Husk:action and give the new tiddler from step 1 the tag Husk:action (and delete the tag action) to get it working. very strange.

(tiddlers are attached. NB: the Husk:action tiddler is the one I ended up using I forgot to save the trouble tiddler, but they look identical)

![billede](https://user-images.githubusercontent.com/2864323/63932427-7119ea00-ca57-11e9-8ec4-73a6cb08e6e0.png)

(tiddlers in .txt so github will accept them)
[Tiddler of the moment.txt](https://github.com/flibbles/tw5-relink/files/3555089/Tiddler.of.the.moment.txt)
[Husk_action.txt](https://github.com/flibbles/tw5-relink/files/3555090/Husk_action.txt)

**Comment by flibbles** [comment]
I cannot seem to replicate this. I have, however, pushed out a bunch of stability fixes in v1.2.1 which might hopefully resolve the situation. If not, then I at least made it so the popped up error says which tiddler it choked on.

Because as much as you were only working with two tiddlers at the time, if your project as more, then _any_ tiddler inside your project might have caused the problem.

Thanks for helping me in cleaning up tw5-relink. Early adopters always get the worst impression.

**Comment by hchaase** [comment]
Thansk you.
> Early adopters always get the worst impression.

I am just exited
