### ISSUE TITLE
[feature reqest] make a warning for known issues that will not be changed

### ISSUE THREAD

**Issue by hchaase** [flibbles/tw5-relink#6]
maybe you could make a warning for [the known issues](https://flibbles.github.io/tw5-relink/#Issues) that will not get updated. Like the "normal" tiddly wiki has the warning for links to this tiddler that will not be updated. This way you could change them manually.

![billede](https://user-images.githubusercontent.com/2864323/63936621-8e06eb00-ca60-11e9-822d-61c364a32695.png)

I am thinking of {{{}}} transclusions, but you probably know the issues better and what will make sense to include.

of course this will not be possible if it is the search for these strings, that is the problem.

**Comment by flibbles** [comment]
The problem with making a pop up like that is that the amount of effort it would take to identify tiddlers Relink doesn't correctly update would equal the amount of work it'd take to just implement the feature.

I do plan to implement filtered transcludes, indirect attributes, and indirect operands within the week, and hopefully then relink will be complete enough to warrant announcing on the Google community page.

I did update the prompt to say "tiddler will be automatically updated" instead of **not** updated. Although it's not completely accurate yet. I will get that to correctly list all tiddlers that will update, but that'll involve writing a filter operator which can perform dry-run relinks.

**Comment by flibbles** [comment]
{{{}}} transclusions are now supported, as are indirect filter operands. With that, the only things that are not are macros (which I'm not sure how that'd even be done) and indirect attribute values.

**Comment by flibbles** [comment]
All but macros are supported (which I'm not certain yet Relink will manage).

The message that appears is actually a completely accurate indicator about what tiddlers will not be updated because of to complex titles (e.g. renaming to `[[title]] 'with' "weird" {{punctuation}}`)

I think this issue is complete as it's going to be. (Except for maybe macros, which will be their own beast)

**Comment by hchaase** [comment]
Thanks 
I appreciate how you just make a even better solution instead.
